[package]
name = "fraile"
version = "0.1.0"
authors = ["Sebastian Nallar"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.23"